### ISSUE TITLE
No wormholes on Archipelago

### ISSUE THREAD

**Issue by ThemInspectors** [Serpens66/DST-Adventure-Mod#2]
as of the current patch when I'm writing this, the game has disabled linking islands with wormholes regardless of world generation setting. I've already contacted a Klei developer about this but who knows how long it will take.

Some workarounds could include manually seeding wormholes in required_setpieces or disabling Archipelago for the time being

**Comment by Serpens66** [comment]
Thanks, I was not able to find out the reason for this, since I set no_wormholes_to_disconnected_tiles = false .
Will try to add them manually.

edit: 
also all other worlds do not have wormholes, not sure what the reason for that is or if it is the same in DS.
edit2: I don't remember how my old code worked, there I already added wormhole1 to wormhole10 somewhere to be able to link them... will try to reactivate this, but first I have to understand it :D

**Comment by Serpens66** [comment]
solved with latest update
